### ISSUE TITLE
Duplicate puns!

### ISSUE THREAD

**Issue by nagendar-pm** [cmcodes1/css-puns#175]
I can see a very funny one 3 times in the pun list. Is this a pun too, but I hardly laughed at it being duplicated thrice..
```css
#titanic {
  float: none;
}
```
I'll work on this if you approve @cmcodes1
